---
title: "CORE121 Election Science Syllabus Spring 2022"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: no
    toc_depth: 4
    self_contained: no
  word_document:
    toc: no
    toc_depth: '4'
  pdf_document:
    toc: no
editor_options:
  markdown:
    wrap: 72
---

```{r setup, include = FALSE, cache = FALSE}
knitr::opts_chunk$set(error = TRUE, comment = NA, warning = FALSE, errors = FALSE, message = FALSE, tidy = FALSE, cache = FALSE)
```

**CORE 121-09 and CORE121-13 Numbers: Election Science**

Section 13 meets MWF at 11:30am - 12:30pm in JR Howard 116\
Section 9 meets MWF at 1:50pm - 2:50pm in JR Howard 254\
Lewis & Clark College\
Spring 2022

Instructor: Ian McDonald, Ph.D.\
Email: [ianmcdonald\@lclark.edu](mailto:ianmcdonald@lclark.edu){.email}
Miller Hall 434\
+1.503.768.7456

Zoom invite link (until Feb 4):
<https://zoom.us/j/96286143040?pwd=UlRjYTBZTXdmQkhvQmRLaG5JZ2Vzdz09>

Office Hours\
Monday and Wednesday 3:30-5 or additional times by appointment. You can
meet with me in person or via teleconferencing.\
Personal zoom link for office hours:
<https://zoom.us/my/ianrmcdonald?pwd=QzVVNG5QMjJSTUlPZ1JTSWszQitTZz09>
passcode: democracy (at one time the code was pD6xtq)

## Syllabus Links

html:
<https://core121-election-science-spring2022.netlify.app/syllabus.html>\
pdf:
<https://core121-election-science-spring2022.netlify.app/syllabus.pdf>

## Course Description

We expect democracies to translate public desire into coherent political
choices. And we expect elections to deliver these results. But
aggregating preferences with elections is harder than it looks. The
simplest elections based on innocent design choices will produce
paradoxical and confounding results.

In this course, we'll introduce mathematical and logical tools that can
help us understand the paradoxes of elections. You will use these tools
to develop and refine your quantitative reasoning skills and apply them
to a fundamental problem: how does adding together individual
preferences make democracy possible? Topics will include redistricting,
voting procedures, and election prediction models. We will look at
contemporary examples such as the recent New York City mayoral primary
election, and the effect of using districts in choosing the Seattle City
Council. You will develop arguments, apply data visualization tools and
consider the relevance of statistical reasoning and causal inference.

This section will teach quantitative reasoning and numeracy skills using
applications related to elections. Currently, scholars employ a wide
variety of quantitative approaches when trying to understand problems of
social choice and democratic outcomes. Topics and data examined in this
section include those related to campaign finance, redistricting, voting
algorithms, voter turnout, polling, and election fraud analysis. You
will learn the production and interpretation of data visualizations,
statistics, and how to design research for causal inference. I will also
introduce you to Microsoft Excel and RStudio.

This class discusses political topics but it is not part of the
college's political science curriculum. It might leverage your interest
in political topics but doesn't require any political knowledge, at all.
We will use politics to demonstrate the power of quantitative reasoning.

## Learning Objectives

At the conclusion of this course, you will be able to:

-   Examine ideas, arguments, biases, and assumptions coming from many
    perspectives, including your own, with an open yet critical mind.
-   Analyze texts and/or quantitative information, recognizing,
    describing, and questioning patterns, trends, anomalies, and
    relationships.
-   Present clear, compelling, and effective arguments and/or analysis,
    supported by evidence.
-   Critically assess numbers and quantitative data as they are employed
    by political scientists, pundits, and the media for understanding
    and predicting political phenomena.
-   Relate issues of diversity, equity, and inclusion to how data is
    gathered, interpreted, and emphasized.
-   Master basic skills in data manipulation and visualization, using
    spreadsheets and other tools.

### Course Website

<https://classroom.google.com/u/0/c/NDUwMzYxODk3MTUw>

This website will be used for both sections. Google Classroom is one of
two sites you will use to submit assignments; the other is My Open Math.
Google Classroom will direct you to the right source for readings and
submissions. This site will also contain all documents and links related
to the course.

The invitation link for Google classroom is
<https://classroom.google.com/c/NDUwMzYxODk3MTUw?cjc=mds6pv2>. The
course code is mds6pv2. Both sections enroll in the same Google
classroom.

## Course Administration

### Course Portals

In this course you will access four different portals that require your
LC id and password for initial contact. Google Classroom will direct you
from session to session, but you will directed to these sites at
different phases of the course.

**My Open Math**\
The first two weekly exercises will come from the website My Open Math.
Sign up using the link below. All material will be directly linked from
our My Open Math class website, so you do not need to regularly check
this site directly. <https://www.myopenmath.com/forms.php?action=enroll>
The course ID: 132786 The enrollment key: democracy

**Google Classroom**\
In addition to serving as the class website, you will submit papers and
your spreadsheet labs through Google Classroom. Enroll using this link:
<https://classroom.google.com/c/NDUwMzYxODk3MTUw?cjc=mds6pv2>

The class code is: mds6pv2

**RStudio**\
You will have a couple of simple labs that will introduce you to the R
programming language. o do that, we'll use a tool called RStudio. You're
not expected to learn any syntax, but you should see this programming
language in action.

You can access RStudio using a web browser and signing in to the
college's server at <https://rstudio.cloud>.

You can use RStudio to explore datasets, generate data visualizations,
and perform simple calculations using the RStudio platform, based on the
R programming language. Dozens of videos and online documents can
provide a background explanation of R, and a good place to start is the
online manual R for Data Science at
<https://r4ds.had.co.nz/introduction.html>.

**R Programming for Beginners** I will introduce you to the R
programming language using the RStudio platform. You don't need to
achieve mastery of R syntax but you should see the basic workflow and
help you recognize situations when R's power in data management and
visualization will help you.

Students looking to develop an advanced skill with payoff in future
classes should explore RStudio. A set of interactive primers can be
found on the RStudio cloud website at:
<https://rstudio.cloud/learn/primers>.

If you want to dive into R, I recommend the R Programming 101 video
series in YouTube. It's entertaining and gentle.

We will have two labs in which you will copy and execute R code in
RStudio and report the results. You will also observe the results of
changing the code slightly. For ambitious data visualization projects,
you may discover that R can satisfy your requirements better than Excel
with a reasonable learning curve.

<https://www.youtube.com/watch?v=nRtp7wSEtJA&list=PLtL57Fdbwb_AWmWWrFV_pLqq2uicpUIO9>

**Microsoft Excel, Google Sheets, and spreadsheets**\
You will also use Microsoft Excel, an ordinary spreadsheet tool, in
labs. You will gain exposure to spreadsheets, and when you compare the
experience to RStudio, you'll see how a scripted programming language
has particular advantages and problems compared to spreadsheet
applications.

Lewis & Clark has a Campus Agreement for Microsoft Office. Because of
this, current students, staff and faculty can use their @lclark.edu
email address to activate a free Office 365 account, which allows them
to use Microsoft apps such as Excel. This program is 100% managed by
Microsoft and is completely separate from Lewis & Clark College.

To set up Office 365:

-   Go to
    <https://products.office.com/en-us/student/office-in-education> to
    sign up.
-   Enter your Lewis & Clark email address
-   Click the Get Started button
-   Access the link that is sent to your email to complete the
    registration
-   Follow the prompts to activate Office 365 and create your Microsoft
    account
-   Install Office and sign-in with your newly created Office 365 ID

If you prefer to use Google sheets, you can complete the exercises in
that tool, but the labs have been written with the downloadable version
of Microsoft Excel in mind.

### Lab Groups

You will work on labs and two group projects, in groups of 3-4.

### Attendance

Your attendance is expected every class session. If you can't attend
class, please notify me. Attendance during the pandemic is more
challenging than usual, but attendance is the easiest thing you can do
to improve your performance in the class.

Your grade will be reduced if you routinely miss class without
notification or reason. See the grade formula below for details.

### Laptops and Phones

If you have access to a laptop computer, you *should* bring it to class
routinely.

You can bring phones into the classroom, but please note that we have
very limited time together and we need to make it count. We all need to
be present and free of distraction. I will count on you to do your part.

Your classroom experience won't be successful if we aren't all focused.
We don't have much time together and we can't afford to waste it.

I will approach you if maintaining focus appears to be a problem.

Please note the Classroom Agreement, and please add anything

### Recording Classes

Lewis & Clark policy generally forbids recording of classes. The policy
states: "...the secret recording (audio or video) of classes, meetings
or other conversations, including telephone calls, is prohibited, as not
compatible with the law or the promotion of an open exchange of ideas."

Please do not record classes without discussing it with me. The concern
is protecting privacy, for everyone in the classroom. See me if you have
questions. The policy is available at
<https://www.lclark.edu/live/profiles/3606-recording-policy>.

### Rescheduling Exams

The exams will take place on the designated days, and cannot be
rescheduled.

### Tutoring at the SQRC

The Symbolic and Quantitative Resource Center (SQRC) is an informal and
free drop-in peer tutoring center. The SQRC will offer both in-person
and remote tutoring this semester. In-person tutoring will take place in
JR Howard 134 and remote tutoring will take place on the SQRC Discord
server. Use this link to join the Discord server:
<https://discord.gg/VWfT99b>

### Changing Sections or Withdrawing

Any requests to change your Words or Numbers section should be directed
to the General Education Office
([GenEd\@lclark.edu](mailto:GenEd@lclark.edu){.email}). Because it is a
required course designed for first year students, withdrawal is not
permitted (unless you are withdrawing from all courses for the
semester).

### Diversity, Equity, and Inclusion

Lewis & Clark and its faculty are committed to diversity, equity, and
inclusion in the classroom. I will work hard to ensure that all
backgrounds and perspectives thrive in this course.

I am committed to the goal that anyone can achieve mastery of basic
quantitative reasoning and the ideas presented in this course.
Typecasting ourselves as a "math" or "non-math" person is self-limiting
and needless.

If your learning needs are not being met, or you do not feel comfortable
with the material being discussed, I am counting on you to let me know.
I will do my best to support a classroom climate that supports a
diversity of thoughts, perspectives, and experiences, and that honors
your identities (including race, gender, class, religion, ability,
etc.). Matters of identity and American politics are inextricably
intertwined and as such will be regularly discussed in class and will
likely require consideration in your research projects.

## Class work and Grading Formula

Our class will ask: How do preferences and choices of individuals in a
democracy translate to political action?

Somehow, a democracy must translate the goals people want into policy,
by adding up preferences, weighing public opinion, and establishing
representation. When we can reason with quantities and measurement, we
can make good judgments about how well we're translating the public's
desires, and how we can improve.

We will also explore how claims concerning these subjects can be argued,
or misrepresented, by data and data visualizations. Some fluency in the
basics of data organization is necessary for quantiative reasoning, and
this fluency does not require mathematics.

The topics in the class include:

-   Surveys, sampling, and the basic of survey computation
-   Using percentages and growth formulas to express political claims
-   Computing voter turnout percentages with spreadsheets and the R
    programming language
-   US House apportionment
-   Districting and Gerrymandering
-   Voting systems, with focus on Ranked Choice Voting
-   The US Electoral College used to elect presidents
-   Political polarization

The class work focuses on mastering the basic computational details of
these topics.

-   Preparation for the capstone presentations and papers
-   Pre-class readings
-   Some exercises using the My Open Math platform
-   Labs and lab submissions using a spreadsheet (presumably Excel) and
    RStudio
-   Two group projects

### Weekly assignments and group projects

35% of total

Most weeks, you will complete a simple assignment that applies your
knowledge about one of the topics. Some of the assignments ask for
answers to questions sets and some are lab completions.

After the break, the weekly assignments shifts to two group projects
that you will submit collectively.

Learning Objectives \#1, \#2, \#3, \#4, and \#5)

### Capstone proposal

10% of total

Submit a first draft of your research project. The draft is due March
14. Your peer review response is due March 16. Your grade will combine
work on both of these tasks.

### Midterm and final exam

10% and 15% of total

The final exam is cumulative. (Learning Objectives \#2 and \#4). The
final exam takes place as scheduled by the college:
<https://college.lclark.edu/offices/registrar/final_exam_schedule/spring/>

Students cannot take the exams with the other section.

The section 9 final exam takes place on Monday, May 2 from 1-4pm in JR
Howard 254.

The section 13 final exam takes place on Wednesday, May 4 from 1-4pm in
JR Howard 116

Each component of the grade is based on a 100 point scale, and I try to
adhere to that formula so that you don't have to reweight the numbers
that you see in assignments or exams in Google classroom.

### Capstone Presentation and Paper

25% of total A final 5-6 page paper (see assignment at
<https://classroom.google.com/c/NDUwMzYxODk3MTUw/a/NDUwOTExMjcwNzU3/details>)

### Attendance/ Participation

5% of total This portion of the grade will be reduced if you routinely
miss class without prior notification or some important reason. Some
sessions will not require in class attendance, and you will know about
those sessions well in advance. Two or more absences will reduce the
score given.

### Grading

In addition, you will present your argument and analysis to the class
and answer questions from your colleagues about your analysis. As part
of this project, you will need to address how your data and analysis
reflects on issues of inclusion, diversity, and equity. (Learning
Objectives \#2, \#3, \#4, and \#5).

**Late work submissions** Unless otherwise specified, late work will be
penalized by 2/3 of a grade per day. This means, for example, that an
assignment graded as a B will be dropped to C+ the first late day, and
to C- the second day. Work submitted more than 48 hours late will not be
accepted.

The grading scale will appear in each assignment description found in
Google Classroom. Assignments will be scored with a number, and the
aggregate of the scores determines your letter grade.

Letter grades will follow this scale: 92-100: A 89-91: A- 86-88: B+
78-85: B 74-77: B- 69-73: C+ 62-68: C 58-61: C- 50-57: D Less than 50: F

## Weekly Assignments (Submissions to Google Classroom)

The first seven graded assignments (before spring break) are worth three
points each. The two group assignments after spring break are worth
eight points each. The first assignment (due on January 19) is ungraded.

Note that I will solicit your input in various ways, through online
surveys and response forms. These solicitations will not be graded, but
will give you chances to test our understanding of ideas that we talk
about, and give me your input about the course.

You will also see ungraded surveys and response forms throughout the
semester, seeking your input about the class as it unfolds.

### Week 1 (due Jan 21)

This assignment is ungraded. Please sign up for these services:

-   Access Microsoft Office and download the office suite:
    <http://www.office.com>

-   Create a FREE account <https://rstudio.cloud>. **Be sure to use the
    Google login option at the bottom of the page, and use your Lewis &
    Clark Google account (the one with the format
    [lc21-XXXX\@lclark.edu](mailto:lc21-XXXX@lclark.edu){.email}).** See
    the assignment for an example

-   Register as a new student at myOpenMath.com: <http://myopenmath.com>
    As noted earlier, the Course ID is **132786** and the passcode is
    **democracy**

-   Make sure you are enrolled in the course portal for Google
    Classroom. <https://classroom.google.com/u/0/c/NDUwMzYxODk3MTUw>

### Week 2 (due Jan 28) {#week-2-due-jan-28}

My Open Math Percentage Problem Solving\
Enter your results in the My Open Math website. We will review the
process in class.\
<https://www.myopenmath.com/course/course.php?cid=132786&folder=0-1>

The assignment is worth three points and you will see your score in
Google Classroom.
<https://classroom.google.com/c/NDUwMzYxODk3MTUw/a/NDUwNjkwNzMyOTk4/details>

### Week 3 (due Feb 4) {#week-3-due-feb-4}

My Open Math Growth Models exercise at
<https://www.myopenmath.com/assess2/?cid=132786&aid=9486788#/>

The assignment is worth three points, and the results will be posted at
<https://classroom.google.com/c/NDUwMzYxODk3MTUw/a/NDUwNzIyNTE2NjU1/details>

### Week 4 (due Feb 11) {#week-4-due-feb-11}

Group Excel Lab \#1
<https://classroom.google.com/c/NDUwMzYxODk3MTUw/a/NDUwODY2OTQ5MTMw/details>

### Week 5 (due Feb 18) {#week-5-due-feb-18}

Identify an election reform proposal, or a data set suitable for the
capstone project.
<https://classroom.google.com/c/NDUwMzYxODk3MTUw/a/NDUwOTEwMTIyNjU0/details>

### Week 6 (due Feb 25) {#week-6-due-feb-25}

Group Excel Lab 2
<https://classroom.google.com/c/NDUwMzYxODk3MTUw/a/NDUwOTYwNTQyMjE4/details>

### Week 7 (no assignment)

### Week 8 (due Mar 11) {#week-8-due-mar-11}

Submit a 300 word summary of the [Gender Studies
symposium](https://college.lclark.edu/departments/gender_studies/symposium/)
at
<https://classroom.google.com/c/NDUwMzYxODk3MTUw/a/NDUwOTE3ODg3NDI5/details>

### Week 9 (due Mar 18) {#week-9-due-mar-18}

Weekly Assignment: Apportionment
<https://classroom.google.com/c/NDUwMzYxODk3MTUw/a/NDUwOTEwMTIyNjU0/details>

### Week 10 (no assignment)

### Week 11 (due Apr 1) {#week-11-due-apr-1}

Group Project \#1: Voting Systems
<https://classroom.google.com/c/NDUwMzYxODk3MTUw/a/NDUwOTYzMTY2Mjgw/details>

### Week 12 (due Apr 8) {#week-12-due-apr-8}

The last weekly assignment Group Project \#2: Gerrymandering
<https://classroom.google.com/c/NDUwMzYxODk3MTUw/a/NDUwOTY1OTE1MzI3/details>

## Course Schedule

### Week 1

#### Wednesday, January 19

**Topic:** A personal course introduction. Syllabus review, a few words
about me, and the purpose of CORE121.

Zoom link for both sections:
<https://zoom.us/j/96286143040?pwd=UlRjYTBZTXdmQkhvQmRLaG5JZ2Vzdz09>

#### Friday, January 21

Reasoning with probability with the Monty Hall Problem.

Zoom link for both sections:
<https://zoom.us/j/96286143040?pwd=UlRjYTBZTXdmQkhvQmRLaG5JZ2Vzdz09>

**Pre-class Reading**:\
Read about the back story of the Monty Hall problem. (No submission but
consider the discussion questions before class.)

<https://www.statisticshowto.com/probability-and-statistics/monty-hall-problem/>\
<https://www.nytimes.com/1991/07/21/us/behind-monty-hall-s-doors-puzzle-debate-and-answer.html>\
<https://www.vox.com/2015/12/1/9821256/monty-hall-problem-mansplainers>

### Week 2

#### Monday, January 24

Manipulating Percentages with Voter Turnout, and the context of voter
turnout.

**Pre-class Homework Assignment:** Read pages 1-6 of this textbook
chapter.
<http://www.opentextbookstore.com/mathinsociety/2.5/ProblemSolving.pdf>

In class we will complete the first three "Try it Now" examples from the
reading.

Zoom link for both sections:
<https://zoom.us/j/96286143040?pwd=UlRjYTBZTXdmQkhvQmRLaG5JZ2Vzdz09>

#### Wednesday, January 26

Using growth formulas: artithmetic vs. geometric/exponential growth.
Political inequality and exponential growth, and the example of wealth
tax.

**Pre-class Reading Assignment**: Read the first 10 pages of PDF at
<http://www.opentextbookstore.com/mathinsociety/2.5/GrowthModels.pdf>.
Read through Example 6, pp. 173-182.

Zoom link for both sections:
<https://zoom.us/j/96286143040?pwd=UlRjYTBZTXdmQkhvQmRLaG5JZ2Vzdz09>

#### Friday, January 28

Assignment Due: [Week 2 (due Jan 28)](#week-2-due-jan-28)

Computing inflation and real dollars

Skim Excel Lab \#1\
<https://classroom.google.com/c/NDUwMzYxODk3MTUw/a/NDUwODY2OTQ5MTMw/details>
...and watch this short video:\
<https://www.youtube.com/watch?v=y_Nt5BL_wgU>

Bacon, Perry Jr. 2021. Why Georgia's New Voting Law is Such a Big Deal.
*FiveThirtyEight* 3/26/2021
<https://fivethirtyeight.com/features/why-georgias-new-voting-law-is-such-a-big-deal>

Zoom link for both sections:
<https://zoom.us/j/96286143040?pwd=UlRjYTBZTXdmQkhvQmRLaG5JZ2Vzdz09>

### Week 3

#### Monday, January 31

Excel lab (Campaign Finance): Turnout computation from simple data in
Excel.

We will finalize lab groups for the semester and begin the lab

Zoom link for both sections:
<https://zoom.us/j/96286143040?pwd=UlRjYTBZTXdmQkhvQmRLaG5JZ2Vzdz09>

#### Wednesday, February 2

Statistics, the difference between Statistics vs. Mathematics.

**Pre-class Reading Assignment \#1**:\
Read Pages 1-11 in
<http://www.opentextbookstore.com/mathinsociety/2.5/Statistics.pdf>

Zoom link for both sections:
<https://zoom.us/j/96286143040?pwd=UlRjYTBZTXdmQkhvQmRLaG5JZ2Vzdz09>

#### Friday, February 4

Assignment Due: [Week 3 (due Feb 4)](#week-3-due-feb-4)

Introduction to Surveys using statistical inference.

**Pre-class Reading Assignment \#1**: Before class, read
<https://www.nytimes.com/2020/11/10/upshot/polls-what-went-wrong.html>
(PDF here:
<https://drive.google.com/file/d/1I0YFrtrBo_PifsvmuhHiwKp-ZEbIo-x7/view?usp=sharing>)\
Zoom link for both sections:
<https://zoom.us/j/96286143040?pwd=UlRjYTBZTXdmQkhvQmRLaG5JZ2Vzdz09>

### Week 4

#### Monday, February 7

As of January 11, this will be our first class in person Data
organization: observations, variables, and description. Read What
Edwards-Levy, Ariel. 2021. Pollsters Think Happened with 2020 Election
Surveys. *CNN.com*
<https://www.cnn.com/2021/05/13/politics/2020-polling-error-research/index.html>
Read
<http://www.opentextbookstore.com/mathinsociety/2.5/DescribingData.pdf>
pp. 247-269. Watch this 7:47 minute video.
<https://www.youtube.com/watch?v=Kno1gJiO5Dg>

#### Wednesday, February 9

Public Opinion and COVID
<https://www.pewresearch.org/2021/03/05/a-year-of-u-s-public-opinion-on-the-coronavirus-pandemic/>

#### Friday, February 11

Assignment Due: [Week 4 (due Feb 11)](#week-4-due-feb-11)

Excel Lab Completion in class

### Week 5

#### Monday, February 14

My Open Math: Collecting Data\
<https://www.myopenmath.com/course/course.php?cid=132786&folder=0-3>
Complete the exercises in the myOpenMath site.

#### Wednesday, February 16

**Topic:**\
Introduction to R and RStudio Lab 1

**Pre-class Homework Assignment \#1**:\
We will recreate the lab described here:
<https://core121-election-science-spring2022.netlify.app/core121-lab-1-v1>
NOTE: We will run the lab in class in real time, and you don't need to try to run it from here before then.

Recommended:  Watch this R Programming 101 video (6:55 in length).
<https://www.youtube.com/watch?v=nRtp7wSEtJA&list=PLtL57Fdbwb_AWmWWrFV_pLqq2uicpUIO9>.

#### Friday, February 18

Assignment Due [Week 5 (due Feb 18)](#week-5-due-feb-18)

Agenda: TBD

### Week 6

#### Monday, February 21

**Topic:**\
Politics and Margins of Error

**Pre-class Reading Assignments:** Read
<https://www.statisticshowto.com/probability-and-statistics/hypothesis-testing/margin-of-error/>

Read
<https://myopenmaths3.s3.amazonaws.com/cfiles/29937/MAT14xTextbook1stEditionCh12.pdf>
(pp. 1-5) AND
<https://myopenmaths3.s3.amazonaws.com/cfiles/2408/ReadingE8.pdf> (pp.
1-4)

#### Wednesday, February 23

Surveys and Public Opinion Part I

**Pre-class Reading Assignment:**
<https://seeing-theory.brown.edu/probability-distributions/index.html>
Read through the interactive online chapters from Chapter 1: Basic
Probability to Chapter 5: Bayesian Inference.

-Jonathan Bernstein. 2020. "Stop Bashing Polls and Learn How to Read
Them."
<https://www.bloomberg.com/opinion/articles/2020-07-05/polls-can-tell-us-who-has-edge-in-presidential-race?srnd=opinion&sref=rMMJuv3g>
-Natalie Jackson. 2020. "Poll-Based Election Forecasts Will Always
Struggle With Uncertainty."
<http://centerforpolitics.org/crystalball/articles/poll-based-election-forecasts-will-always-struggle-with-uncertainty/>

#### Friday, February 25

Assignment Due: [Week 6 (due Feb 25)](#week-6-due-feb-25)

Surveys and Public Opinion Part II -Harry Enten. 2021. "Why the polls
were off in 2020."
<https://www.cnn.com/2021/04/13/politics/democratic-pollsters-2020-analysis/index.html>
-Andrew Gelman. 2020. "Probabilistic forecasts cause general
misunderstanding. What to do about this?"
<https://statmodeling.stat.columbia.edu/2020/08/09/probabilistic-forecasts-cause-general-misunderstanding-what-to-do-about-this/>
-Aubrey Clayton. 2019. "How to Improve Political Forecasts."
<http://nautil.us/issue/70/variables/how-to-improve-political-forecasts>

### Week 7

#### Monday, February 28

Voting Theory Part 1: Ordering preference and preference tables Read
<http://www.opentextbookstore.com/mathinsociety/2.5/VotingTheory.pdf>
(pp. 35-43)

#### Wednesday, March 2

Ranked Choice Voting and the New York Mayoral Primary
<https://www.thecity.nyc/2021/7/19/22584637/did-ranked-choice-voting-work-in-nyc-eric-adams>

#### Friday, March 4

Midterm Exam

### Week 8

#### Monday, March 7

Voting Systems (continued) Apportionment and the U.S. House of
Representatives

**Topic:**\
Apportionment and the U.S. House of Representatives.

**Pre-class Reading Assignment** Read
<https://www.ianrmcdonald.com/posts/2021-05-10-new-york-and-house-apportionment-in-2020_update/>

Peer review response

#### Wednesday, March 9

GENDER SYMPOSIUM

#### Friday, March 11

Assignment Due: [Week 8 (due Mar 11)](#week-8-due-mar-11)

GENDER SYMPOSIUM

### Week 9

#### Monday, March 14

**Topic:** Gerrymandering in the United States and the Group Voting
Rules project.

Read
<https://www.quantamagazine.org/the-math-behind-gerrymandering-and-wasted-votes-20171012/>
and come prepared to discuss this question:

"What is the definition of gerrymandering, and how can we use the
efficiency gap to measure it?"

We will also stqage the voting systems group project. Your group will be
responsible for defining the outcome of the New York mayoral primary
using Approval Voting. You will apply a common dataset to the project.

#### Wednesday, March 16

Gerrymandering and the politics of geography: More on the efficiency
gap, measuring gerrymandering, and Seattle City Council Switches to
Districts

**Preclass Reading Assignment:** Read
<https://sccinsight.com/2021/03/19/understanding-the-city-council-redistricting-process/>
and come prepared to answer this question: "Why would Seattle voters
have chosen to adopt a district based system in 2013, given all the
uncertainty about managing and defining districts? Isn't that going
backwards?"

#### Friday, March 18

Assignment Due: [Week 9 (due Mar 18)](#week-9-due-mar-18)

Your Data Project and Presentation.

We will discuss the end-of-semester data projects, which include a
presentation and a short paper. The presentations will cover the final
five days of class, and the paper (2-3 pages) is due Wednesday, April
27.

The implications of district building with Dave's Redistricting tool and
District Builder.\
**Pre-class Video Assignment** Watch this video (13:38 minutes):
<https://www.youtube.com/watch?v=Pp42Rw2cVQA> and peruse the online tool
at <https://davesredistricting.org/maps#home>\
We will compare this tool to <https://www.districtbuilder.org/> if time
permits

### Week 10

Monday, March 21 - Friday, March 25: Spring Break

### Week 11

#### Monday, March 28

Principles of Data Visualization

**Preclass Reading Assignment:** Read
<https://fivethirtyeight.com/features/the-52-best-and-weirdest-charts-we-made-in-2016/>
<https://towardsdatascience.com/data-visualization-101-7-steps-for-effective-visualizations-491a17d974de>
Read <https://www.livescience.com/45083-misleading-gun-death-chart.html>
Read <https://badvisualisations.tumblr.com/>

#### Wednesday, March 30

Principles of Data Visualization

#### Friday, April 1

Assignment Due: [Week 11 (due Apr 1)](#week-11-due-apr-1)

Datawrapper workshop

Look at this overview of an app called datawrapper.
<https://www.datawrapper.de/maps>

### Week 12

#### Monday, April 4

Using District Building and Dave's Redistricing Tool

Watch this video (13:38 minutes):
<https://www.youtube.com/watch?v=Pp42Rw2cVQA> and peruse the online tool
at <https://davesredistricting.org/maps#home>\
We will compare this tool to <https://www.districtbuilder.org/> if time
permits

#### Wednesday, April 6

#### Friday, April 8

Assignment Due: [Week 12 (due Apr 8)](#week-12-due-apr-8)

Festival of Scholars: No class today

### Week 13

#### Monday, April 11

The U.S. Electoral College

**Preclass Reading Assignment:** Read
<https://www.nytimes.com/article/the-electoral-college.html> AND
<https://www.nationalpopularvote.com/written-explanation>.

Come prepared to answer this question: "Maine and Nebraska don't use
winner-take-all allocations of their electors. Why don't the other 48
states and DC follow their lead?"

#### Wednesday, April 13

**Topic:**\
Polarization

**Pre-class Reading Assignment:** Read this article: Mason, Lilliana.
2018. Losing Common Ground: Social Sorting and Polarization *The Forum*
v.18(1) <https://bit.ly/3go9bZa>

#### Friday, April 15

Presentations

### Week 14

#### Monday, April 18

Presentations

#### Wednesday, April 20

Presentations

#### Friday, April 22

### Week 14

#### Monday, April 25

Presentations

#### Wednesday, April 27

Final Exam Review

Capstone Paper is Due:
<https://classroom.google.com/c/Mzc2MjMzMzQ1ODU0/a/NDI1MjM4NzAwODE1/details>

### Week 15

#### Monday, May 2

Section 9 Final Exam: 1-4pm

#### Wednesday, May 4

Section 13 Final Exam: 1-4pm
